[package]
name = "aoc2015"
version = "0.1.0"
authors = ["dseres"]
edition = "2018"
publish = false

[dependencies]
md5 = "0.6.1"
regex = "1.6.*"
lazy_static = "1.2.0"
permutohedron = "0.2.4"
json = "0.11.13"
permutator = "0.3.3"
multimap = "0.4.0"
